defaults: &defaults
  working_directory: ~/reg-cli
  docker:
    - image: reg-viz/node-xcb

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm i
      - run:
          name: Test
          command: |
            npm run test
            npm reg-suit run
  patch_releasenpm :
    <<: *defaults
    steps:
      - add-ssh-keys:
          fingerprints:
            - "df:c6:25:54:15:dd:05:63:b5:e0:c3:ae:56:6b:8b:95"
      - checkout
      - run:
          name: Install dependencies
          command: npm 
      - run:
          name: Build
          command: npm run build
      - run:
          name: Setup git
          command: |
            git config --global user.email "bokuweb12@gmail.com"
            git config --global user.name "bokuweb"
      - run:
          name: Login npm
          command: |
            echo "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}" > ~/.npmrc
            npm whoami
      - run:
          name: Publish to npm
          command: |
            git reset --hard HEAD
            npm version patch
            npm publish           
            git push origin master
            git push --tags
  minor_release:
    <<: *defaults
    steps:
      - add-ssh-keys:
          fingerprints:
            - "df:c6:25:54:15:dd:05:63:b5:e0:c3:ae:56:6b:8b:95"
      - checkout
      - run:
          name: Install dependencies
          command: npm
      - run:
          name: Build
          command: npm run build          
      - run:
          name: Setup git
          command: |
            git config --global user.email "bokuweb12@gmail.com"
            git config --global user.name "bokuweb"
      - run:
          name: Login npm
          command: |
            echo "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}" > ~/.npmrc
            npm whoami
      - run:
          name: Publish to npm
          command: |
            git reset --hard HEAD
            npm version minor
            npm publish
            git push origin master
            git push --tags
workflows:
  version: 2
  build_pipeline:
    jobs:
      - build
      - confirm_patch:
          type: approval
          filters:
            branches:
              only: master
          requires:
            - build
      - confirm_minor:
          type: approval
          filters:
            branches:
              only: master
          requires:
            - build
      - patch_release:
          filters:
            branches:
              only: master
          requires:
            - confirm_patch
      - minor_release:
          filters:
            branches:
              only: master
          requires:
            - confirm_minor
