defaults: &defaults
  working_directory: ~/reg-cli
  docker:
    - image: bokuweb/node-go-with-browser:latest
      environment:
        DISPLAY: ":99"

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-cache-{{ checksum "yarn.lock" }}-{{ checksum "package.json" }}
            - npm-cache
      - run:
          name: Install dependencies
          command: yarn install --pure-lockfile
      - save_cache:
          key: npm-cache-{{ checksum "yarn.lock" }}-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Test
          command: |
            yarn run flow
            yarn run test
            yarn reg-suit run
  patch_release:
    <<: *defaults
    steps:
      - add-ssh-keys:
          fingerprints:
            - "df:c6:25:54:15:dd:05:63:b5:e0:c3:ae:56:6b:8b:95"
      - checkout
      - run:
          name: Install dependencies
          command: yarn install --pure-lockfile
      - restore_cache:
          keys:
            - npm-cache-{{ checksum "yarn.lock" }}-{{ checksum "package.json" }}
            - npm-cache
      - run:
          name: Build
          command: |
            yarn run build          
      - run:
          name: Setup git
          command: |
            git config --global user.email "bokuweb12@gmail.com"
            git config --global user.name "bokuweb"
      - run:
          name: Login npm
          command: |
            echo "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}" > ~/.npmrc
            npm whoami
      - run:
          name: Publish to npm
          command: |
            npm version patch
            npm publish           
            git push origin master
            git push --tags
  minor_release:
    <<: *defaults
    steps:
      - add-ssh-keys:
          fingerprints:
            - "df:c6:25:54:15:dd:05:63:b5:e0:c3:ae:56:6b:8b:95"
      - checkout
      - restore_cache:
          keys:
            - npm-cache-{{ checksum "yarn.lock" }}-{{ checksum "package.json" }}
            - npm-cache
      - run:
          name: Install dependencies
          command: yarn install --pure-lockfile
      - run:
          name: Build
          command: |
            yarn run build          
      - run:
          name: Setup git
          command: |
            git config --global user.email "bokuweb12@gmail.com"
            git config --global user.name "bokuweb"
      - run:
          name: Login npm
          command: |
            echo "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}" > ~/.npmrc
            npm whoami
      - run:
          name: Publish to npm
          command: |
            npm version minor
            npm publish
            git push origin master
            git push --tags
workflows:
  version: 2
  build_pipeline:
    jobs:
      - build
      - confirm_patch:
          type: approval
          filters:
            branches:
              only: master
          requires:
            - build
      - confirm_minor:
          type: approval
          filters:
            branches:
              only: master
          requires:
            - build
      - patch_release:
          filters:
            branches:
              only: master
          requires:
            - confirm_patch
      - minor_release:
          filters:
            branches:
              only: master
          requires:
            - confirm_minor
