defaults: &defaults
  working_directory: ~/reg-cli
  docker:
    - image: quramy/node-nightmare
      environment:
        DISPLAY: ":99"

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Test
          command: |
            xvfbd start
            yarn run flow
            yarn run test
            yarn reg-suit run
            xvfbd stop          
  patch_release:
    <<: *defaults
    steps:
      - add-ssh-keys:
          fingerprints:
            - "df:c6:25:54:15:dd:05:63:b5:e0:c3:ae:56:6b:8b:95"
      - checkout
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Build
          command: |
            yarn run build          
      - run:
          name: Setup git
          command: |
            git config --global user.email "bokuweb12@gmail.com"
            git config --global user.name "bokuweb"
      - run:
          name: Login npm
          command: |
            echo "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}" > ~/.npmrc
            npm whoami
      - run:
          name: Publish to npm
          command: |
            git reset --hard HEAD
            yarn run copy:ximgdiff
            VER=`npm version patch`
            yarn pack
            npm publish reg-cli-$VER.tgz --unsafe-perm   
            git push origin master
            git push --tags
  minor_release:
    <<: *defaults
    steps:
      - add-ssh-keys:
          fingerprints:
            - "df:c6:25:54:15:dd:05:63:b5:e0:c3:ae:56:6b:8b:95"
      - checkout
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Build
          command: |
            yarn run build          
      - run:
          name: Setup git
          command: |
            git config --global user.email "bokuweb12@gmail.com"
            git config --global user.name "bokuweb"
      - run:
          name: Login npm
          command: |
            echo "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}" > ~/.npmrc
            npm whoami
      - run:
          name: Publish to npm
          command: |
            git reset --hard HEAD
            yarn run copy:ximgdiff
            VER=`npm version minor`
            yarn pack
            npm publish reg-cli-$VER.tgz --unsafe-perm 
            git push origin master
            git push --tags
workflows:
  version: 2
  build_pipeline:
    jobs:
      - build
      - confirm_patch:
          type: approval
          filters:
            branches:
              only: master
          requires:
            - build
      - confirm_minor:
          type: approval
          filters:
            branches:
              only: master
          requires:
            - build
      - patch_release:
          filters:
            branches:
              only: master
          requires:
            - confirm_patch
      - minor_release:
          filters:
            branches:
              only: master
          requires:
            - confirm_minor
